### ISSUE TITLE
Запуск сервера на ubuntu

### ISSUE THREAD

**Issue by Kverde** [AndyGrom/node-deploy-server#5]
При запуске сервера командой появляется ошибка:
root@33503:/etc/init.d# service nodehosting start
env: /etc/init.d/nodehosting: No such file or directory

На windws сервер нормально запускается.

**Comment by AndyGrom** [comment]
Which version of Ubuntu?

**Comment by Kverde** [comment]
```
root@33503:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic
```

**Comment by AndyGrom** [comment]
Reinstall please node-deploy-server.
I`m updated npm repository.
